### ISSUE TITLE
LuaGuiElement API call when LuaGuiElement was invalid, maybe caused by LTN Tracker

### ISSUE THREAD

**Issue by eduran84** [Klonan/Unit_Control#1]
Could you have a look at [this bug report](https://forums.factorio.com/viewtopic.php?f=214&t=64842&start=40#p405784)? I think the error is caused by Unit Control, but it might be triggered by something LTN Tracker is doing.
This is my toggle function:
```
function gcOuterFrame:toggle(pind)
  local new_state = GC.toggle(self, pind)
  if new_state then
    game.players[pind].opened = self:get(pind)
  else
    game.players[pind].opened = nil
  end
  global.gui.is_gui_open[pind] = new_state
  return new_state
end
```
Could setting game.players[pind].opened to nil cause the issue? Is it something that needs fixing on my end or your end?

**Comment by Klonan** [comment]
I didn't see this sorry, its better to report bugs on the forum thread.

I will fix it on my end
